import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Transaction from './transaction'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Split ADA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
        <h1 style={{display:'flex', justifyContent:'center', fontWeight:'bold', color:'powderblue' ,paddingBottom:'30px'}}>Split ADA</h1>
          <Transaction/>
        </div>
      </main>
    </>
  )
}
